---
abstract: 'map relational database to RDF declaratively'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  DBD::SQLite: 0
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
keywords:
  - DBI
  - Database
  - 'Direct Mapping'
  - R2R
  - R2RML
  - RDB2RDF
  - RDBMS
  - RDF
  - SQL
  - 'Semantic Web'
  - Turtle
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: RDF::RDB2RDF
name: RDF-RDB2RDF
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  DBI: 0
  Data::UUID: 0
  JSON: 2.00
  MIME::Base64: 0
  RDF::Trine: 0.135
  URI::Escape: 0
  namespace::clean: 0.19
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=RDF-RDB2RDF
  homepage: https://metacpan.org/release/RDF-RDB2RDF
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-rdf-rdb2rdf
version: 0.007
